// SPDX-License-Identifier: Apache-2.0

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { format } from 'prettier';
import { z } from 'zod';

import type { ExposureProfile } from '../src/core/coverage/types.js';
import {
  DEFAULT_TOOL_FEATURE_FLAGS,
  listManagedToolsForProfile,
  type ManagedToolDefinition,
  type ToolFeatureFlagName,
} from '../src/mcp/registry.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repositoryRoot = path.resolve(__dirname, '..');
const generatedDirectory = path.join(repositoryRoot, 'docs', 'generated');

const profiles: ExposureProfile[] = ['safe', 'ops', 'admin', 'all'];
const allFeatureFlagsEnabled = {
  ...DEFAULT_TOOL_FEATURE_FLAGS,
  allowAuthAdminTools: true,
  allowMcpbUpload: true,
  allowStdioServerCreate: true,
  allowSystemConfigWrite: true,
};

type GeneratedToolEntry = {
  annotations: {
    destructiveHint: boolean;
    idempotentHint: boolean;
    openWorldHint: boolean;
    readOnlyHint: boolean;
  };
  confirmationRequired: boolean;
  description: string;
  inputFields: Array<{
    description: string | null;
    name: string;
    optional: boolean;
  }>;
  profile: ExposureProfile;
  requiredFeatureFlags: ToolFeatureFlagName[];
  risk: string;
  sinceMcphubVersion: string;
  tool: string;
  upstream: {
    method: string;
    path: string;
  };
};

function isZodObject(schema: z.ZodType | undefined): schema is z.ZodObject {
  return schema instanceof z.ZodObject;
}

function getInputFields(schema: z.ZodType | undefined): GeneratedToolEntry['inputFields'] {
  if (!isZodObject(schema)) {
    return [];
  }

  const shape = schema.shape as Record<string, z.ZodType>;

  return Object.entries(shape).map(([name, fieldSchema]) => {
    const description =
      typeof fieldSchema.description === 'string' ? fieldSchema.description : null;
    const optional = fieldSchema.safeParse(undefined).success;

    return {
      description,
      name,
      optional,
    };
  });
}

function requiresConfirmation(schema: z.ZodType | undefined): boolean {
  return getInputFields(schema).some((field) => field.name === 'confirm');
}

function buildGeneratedEntry(tool: ManagedToolDefinition): GeneratedToolEntry {
  return {
    annotations: {
      destructiveHint: tool.annotations.destructiveHint === true,
      idempotentHint: tool.annotations.idempotentHint === true,
      openWorldHint: tool.annotations.openWorldHint === true,
      readOnlyHint: tool.annotations.readOnlyHint === true,
    },
    confirmationRequired: requiresConfirmation(tool.inputSchema),
    description: tool.description,
    inputFields: getInputFields(tool.inputSchema),
    profile: tool.coverage.profile as ExposureProfile,
    requiredFeatureFlags: tool.requiredFeatureFlags,
    risk: tool.coverage.risk ?? 'unknown',
    sinceMcphubVersion: tool.coverage.sinceMcphubVersion,
    tool: tool.name,
    upstream: {
      method: tool.coverage.method,
      path: tool.coverage.path,
    },
  };
}

function renderProfileMarkdown(profile: ExposureProfile, entries: GeneratedToolEntry[]): string {
  const rows = entries
    .map((entry) => {
      const flags =
        entry.requiredFeatureFlags.length === 0
          ? '-'
          : entry.requiredFeatureFlags.map((flag) => `\`${flag}\``).join(', ');
      const confirmation = entry.confirmationRequired ? 'yes' : 'no';

      return `| \`${entry.tool}\` | \`${entry.profile}\` | \`${entry.risk}\` | \`${entry.upstream.method}\` | \`${entry.upstream.path}\` | ${flags} | ${confirmation} | ${entry.description} |`;
    })
    .join('\n');

  return `# ${profile} Tool Catalog

This document is generated by \`pnpm docs:tools\`.

It includes the full tool surface for the \`${profile}\` profile with dangerous feature flags explicitly enabled for documentation purposes.

| Tool | Profile | Risk | Method | Path | Feature Flags | Confirm | Description |
| --- | --- | --- | --- | --- | --- | --- | --- |
${rows}
`;
}

function renderGeneratedIndex(counts: Array<{ count: number; profile: ExposureProfile }>): string {
  const rows = counts
    .map(
      ({ count, profile }) =>
        `| \`${profile}\` | ${String(count)} | [tools.${profile}.md](./tools.${profile}.md) | [tools.${profile}.json](./tools.${profile}.json) |`,
    )
    .join('\n');

  return `# Generated Catalogs

This directory is generated from the tool registry and coverage matrix.

## Tool Catalogs

| Profile | Tools | Markdown | JSON |
| --- | --- | --- | --- |
${rows}

## Coverage

- [api-coverage.json](./api-coverage.json): machine-readable coverage export derived from the canonical matrix.

## Regeneration

- Run \`pnpm docs:tools\` to refresh the tool catalogs.
- Run \`pnpm docs:coverage\` to refresh the coverage markdown and JSON.
- Run \`pnpm docs:tools:check\` and \`pnpm docs:coverage:check\` in CI to detect drift.
`;
}

async function writeFileIfChanged(
  filePath: string,
  contents: string,
  checkMode: boolean,
): Promise<void> {
  const formattedContents = await format(contents, { filepath: filePath });
  const current = readFileSync(filePath, 'utf8');
  if (current !== formattedContents) {
    if (checkMode) {
      throw new Error(
        `${path.relative(repositoryRoot, filePath)} is out of date. Run the matching docs command.`,
      );
    }

    writeFileSync(filePath, formattedContents, 'utf8');
  }
}

async function ensureFile(filePath: string, contents: string, checkMode: boolean): Promise<void> {
  try {
    await writeFileIfChanged(filePath, contents, checkMode);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      if (checkMode) {
        throw new Error(
          `${path.relative(repositoryRoot, filePath)} is missing. Run "pnpm docs:tools".`,
        );
      }

      writeFileSync(filePath, await format(contents, { filepath: filePath }), 'utf8');
      return;
    }

    throw error;
  }
}

async function main(): Promise<void> {
  const checkMode = process.argv.includes('--check');
  mkdirSync(generatedDirectory, { recursive: true });

  const counts: Array<{ count: number; profile: ExposureProfile }> = [];

  for (const profile of profiles) {
    const entries = listManagedToolsForProfile(profile, allFeatureFlagsEnabled)
      .map(buildGeneratedEntry)
      .sort((left, right) => left.tool.localeCompare(right.tool));

    counts.push({ count: entries.length, profile });

    const markdownPath = path.join(generatedDirectory, `tools.${profile}.md`);
    const jsonPath = path.join(generatedDirectory, `tools.${profile}.json`);

    await ensureFile(markdownPath, renderProfileMarkdown(profile, entries), checkMode);
    await ensureFile(jsonPath, `${JSON.stringify(entries, null, 2)}\n`, checkMode);
  }

  const indexPath = path.join(generatedDirectory, 'README.md');
  await ensureFile(indexPath, renderGeneratedIndex(counts), checkMode);
}

await main();
