// SPDX-License-Identifier: Apache-2.0

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  AUTOMATED_COMPATIBILITY_IMAGE_TAGS,
  COMPATIBILITY_NOTES_SUMMARY,
  ROUTE_SNAPSHOT_BASELINE_VERSION,
  UPSTREAM_COMPATIBILITY_TARGETS,
} from '../src/core/compatibility/targets.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repositoryRoot = path.resolve(__dirname, '..');
const outputPath = path.join(repositoryRoot, 'docs', 'compatibility.md');
const packageJsonPath = path.join(repositoryRoot, 'package.json');

type PackageJsonShape = {
  dependencies?: Record<string, string>;
};

function readSdkRange(): string {
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8')) as PackageJsonShape;
  return packageJson.dependencies?.['@modelcontextprotocol/sdk'] ?? 'unknown';
}

function buildCompatibilityDocument(): string {
  const sdkRange = readSdkRange();
  const compatibilityRows = UPSTREAM_COMPATIBILITY_TARGETS.map(
    (target) => `| \`${target.label}\` | ${target.status} | ${target.notes} |`,
  ).join('\n');
  const automatedMatrixDescription = AUTOMATED_COMPATIBILITY_IMAGE_TAGS.map((tag) => `\`${tag}\``).join(', ');

  return `# Compatibility

This document is generated by \`pnpm docs:compatibility\`.

## MCPHub Compatibility

| MCPHub version | Status | Notes |
| --- | --- | --- |
${compatibilityRows}

## Automated Matrix

- \`pnpm test:compatibility\` runs the real-container smoke suite in \`tests/integration/upstream-compat.test.ts\`.
- Set \`RUN_MCPHUB_COMPAT_TESTS=1\` to enable the suite locally.
- Optionally scope the suite with \`MCPHUB_COMPAT_IMAGE_TAG=<tag>\`.
- GitHub Actions runs the compatibility matrix on ${automatedMatrixDescription}.

## MCP Transport Compatibility

| Transport mode | Status | Notes |
| --- | --- | --- |
| stdio | supported | current stable local transport |
| Streamable HTTP \`stateful\` | supported | \`2025-11-25\` era handshake via the current npm-released SDK line |
| Streamable HTTP \`stateless\` | supported | \`2026-07-28\` era POST-only mode with header/body validation |
| SSE | not supported | intentionally omitted |

## MCP Client Compatibility

| Client era | Recommended server mode | Notes |
| --- | --- | --- |
| Legacy \`2025-11-25\` and earlier | \`MCP_HTTP_MODE=stateful\` | Works with the SDK range declared in \`package.json\` (\`${sdkRange}\`) |
| Modern \`2026-07-28\` | \`MCP_HTTP_MODE=stateless\` | Use raw JSON-RPC over HTTP today; header/body validation is enforced server-side |
| Dual-era deployments | separate listeners or a deliberate rollout plan | The repository keeps both modes available behind one env flag rather than auto-negotiating eras inside one process path |

## Notes

- Route coverage is still generated from the pinned \`${ROUTE_SNAPSHOT_BASELINE_VERSION}\` upstream snapshot.
- ${COMPATIBILITY_NOTES_SUMMARY}
- If upstream adds new endpoints, route-drift and coverage checks should fail until the matrix is updated.
`;
}

function main(): void {
  const expected = buildCompatibilityDocument();
  const checkMode = process.argv.includes('--check');

  if (checkMode) {
    const current = readFileSync(outputPath, 'utf8');
    if (current !== expected) {
      throw new Error('docs/compatibility.md is out of date. Run "pnpm docs:compatibility".');
    }

    return;
  }

  writeFileSync(outputPath, expected, 'utf8');
}

main();
